---
- name: Copy shell scripts library to remote host
  copy:
    src: "{{ role_path }}/files/shell_lib.sh"
    dest: "$HOME/.ansible/tmp/shell_lib.sh"
  tags: ['configure_rpi_network']

- name: Configure RPi network settings
  tags: ['configure_rpi_network']
  script: raspi_config_network.sh
  register: scriptOut
  async: 0
  poll: 0
  ignore_errors: false
  # become: true
  environment:
    HOST_NAME: "{{ host_name | mandatory }}"
    WIFI_COUNTRY: "{{ wifi_country | default('') }}"
    WIFI_SSID_PASSPHRASE: "{{ wifi_ssid_passphrase | default('') }}"

- debug: msg={{ scriptOut.stdout }}
  tags: ['configure_rpi_network']
