version: 2
updates:
  - package-ecosystem: pip
    directory: "/provisioner_examples_plugin"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - ZachiNachshon
  - package-ecosystem: pip
    directory: "/provisioner_installers_plugin"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - ZachiNachshon
  - package-ecosystem: pip
    directory: "/provisioner_single_board_plugin"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - ZachiNachshon