name: 'Setup Environment'
description: 'Install workflow necessities'
runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    # 
    # Temporary disable caching since the upload time takes longer than the actual action time
    # 
    # - name: (Cache) Try Load - Poetry Installation
    #   id: cached-poetry
    #   uses: actions/cache@v3
    #   with:
    #     path: ~/.local                         # Path depends on the OS
    #     key: poetry-${{ env.POETRY_VERSION }}  # Change to reset cache

    - name: (Install) Poetry
      if: steps.cached-poetry.outputs.cache-hit != 'true'
      uses: snok/install-poetry@v1
      with:
        version: ${{ env.POETRY_VERSION }}
      
    - name: (Install) Poetry Plugins
      run: |
        poetry self add poetry-multiproject-plugin
      shell: bash
      
    - name: (Config) Set Poetry Python shared virtual environment for all projects
      run: |
        poetry config virtualenvs.path "${{ github.workspace }}/.venv"
      shell: bash

    # 
    # Temporary disable caching since the upload time takes longer than the actual action time
    # 
    # - name: (Cache) Try Load - gh
    #   id: cache-gh
    #   uses: actions/cache@v3
    #   with:
    #     path: /usr/local/bin/gh
    #     key: provisioner-cache-gh-client-${{ runner.os }}

    - name: (Install) gh
      if: steps.cache-gh.outputs.cache-hit != 'true'
      run: |
        curl -sSL https://github.com/cli/cli/releases/download/v2.41.0/gh_2.41.0_linux_amd64.tar.gz | tar xz
        sudo mv gh_*_linux_amd64/bin/gh /usr/local/bin/
        gh --version
      shell: bash