os:
  raspbian:
    first_boot_username: pi
    first_boot_password: provisioner
    download_path: $HOME/.config/provisioner/images/raspios
    active_system: 64bit
    download_url:
      url_64bit: https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2024-11-19/2024-11-19-raspios-bookworm-arm64-lite.img.xz
      url_32bit: https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2024-11-19/2024-11-19-raspios-bookworm-armhf-lite.img.xz

network:
  gw_ip_address: 192.168.1.1
  dns_ip_address: 192.168.1.1

remote:
  hosts:
    - name: localhost
      address: ansible_connection=local
      auth:
        username: pi
        password: raspberry
    - name: k3s-master
      address: 192.168.1.200
      auth:
        username: pi
        password: Clusterring123

  lan_scan:
    ip_discovery_range: 192.168.1.1/24

