---
- name: Run k3s master installation command
  tags: ['k3s_master_install']
  script: master_install.sh
  register: scriptOut

- debug: msg={{ scriptOut.stdout }}
  tags: ['k3s_master_install']

- name: Validating k3s master status - active (running)
  tags: ['k3s_master_install']
  changed_when: False # nothing really gets changed
  no_log: True
  command: systemctl status k3s
  ignore_errors: true
  register: svcOut
  until: '"active (running)" in svcOut.stdout'
  retries: 5
  delay: 10

- name: Fail the play if the previous command did not succeed
  tags: ['k3s_master_install']
  fail: msg="Failed to validate k3s master is running successfully"
  when: '"active (running)" not in svcOut.stdout'
