---
- name: Playbook for shutting down a remote machine
  hosts: selected_hosts
  gather_facts: no
  tasks:
    - name: Shutdown a remote node
      become: true
      shell: shutdown -h now
      async: 0
      poll: 0
      ignore_errors: true

    - name: "Wait for shutdown to complete"
      local_action: wait_for host={{ ansible_ssh_host }} port=22 state=stopped

#    - name: "Wait for shutdown to complete"
#      local_action: wait_for host={{ ansible_host }} port=22 state=stopped
#      become: false