---
- name: Provisioner run command
  hosts: selected_hosts
  gather_facts: no
  environment:
    DRY_RUN: True
    VERBOSE: True
    # SILENT: True

  roles:
    - role: external/ansible_playbooks/playbooks/roles/provisioner
      tags: ['provisioner_run']
