[tool.poetry]
name = "provisioner_examples_plugin"
version = "0.1.0"
description = "Python Examples Library"
authors = ["Zachi Nachshon <zachi.nachshon@gmail.com>"]
exclude = [
    "**/*_test*", 
    "**/*_fake*", 
    "dist", 
    "htmlcov", 
    "poetry.lock", 
    "pytest", 
    "Makefile", 
    "runners", 
    ".gitignore",
    ".coverage",
    ".coveragerc",
    ".git-deps",
    ".pycache"]

# A list of patterns that will be included in the final package.
# If no format is specified, it will default to include both sdist and wheel
# i.e. { path = "tests", format = ["sdist", "wheel"] }
# include = [
#     { path = "../../provisioner_features_lib" },
# ]

[tool.poetry.scripts]
# This module is not meant to be used as a standalone CLI, rather used as a plugin/library for a module with a main entry point i.e. provisioner
test_runner = "provisioner_examples_plugin.main_fake:fake_app"
# For debugging proposes when running "poetry run provisioner" from within the plugins folder
# provisioner = "provisioner.main:main"
example_plugin = "provisioner_examples_plugin.main_dev:main"

[tool.black]
line-length = 120

[tool.ruff]
exclude = [".venv", "external", ".git-deps"]
line-length = 120
ignore = [ "E501", "E402", "F403", "F405" ]
select = [
    # Pyflakes
    "F",
    # Pycodestyle
    "E",
    # isort
    "I",
    # Whitespaces
    "W", 
]

[tool.mypy]
exclude = ["external"]
ignore_missing_imports = "True"
check_untyped_defs = "True"
disallow_untyped_defs = "True"
disallow_incomplete_defs = "True"
disallow_untyped_decorators = "True"
disallow_any_unimported = "False" # Generates an error if a component of a type becomes Any because mypy couldn’t resolve an import
warn_return_any = "False" # Generates an error if you return a value with an Any type in a function that is annotated to return a non-Any value
warn_unused_ignores = "True"
no_implicit_optional = "True"
show_error_codes = "True"

[tool.poetry.dependencies]
python = "^3.10"
typer = "^0.6.1"
loguru = "^0.6.0"
requests = "^2.28.1"
# Progress Bar for Python and CLI (https://github.com/Textualize/rich)
rich = "^12.5.1"
python3-nmap = "^1.5.4"
python-libnmap = "^0.7.3"
PyYAML = "^6.0"
inquirer = "^2.10.0"
python-hosts = "^1.0.3"
# When using the dev-dependencies, the provisioner will be installed from the local folder
# Those two lines should be commented out when running "poetry install" from within the plugins folder
# To perform a clean build:
#  - Remove poetry.lock file
#  - Remove the .venv folder
#  - Run "make deps" from within the plugins folder
# provisioner_features_lib = { git = "git@github.com:ZachiNachshon/provisioner.git", branch = "master", rev = "573c195", subdirectory = "provisioner_features_lib" }
provisioner = { path = "../../provisioner", develop = false }
provisioner_features_lib = { path = "../../provisioner_features_lib", develop = false }

[tool.poetry.dev-dependencies]
black = "^22.8.0"
pytest = "^7.1.3"
mypy = "^0.991"
coverage = "^6.4.4"
diagrams = "^0.22.0"
ruff = "^0.0.265"
poetry-multiproject-plugin = "^1.3.3"

# For debugging purposes when running "poetry run provisioner" from within the plugins folder
# Make sure to comment out the provisioner line under [tool.poetry.scripts]
# When building for production, remember to comment out this line
provisioner = { path = "../../provisioner", develop = true }
provisioner_features_lib = { path = "../../provisioner_features_lib", develop = true }


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"