---
- name: Configure static IP address and hostname on remote RPi host
  hosts: selected_hosts
  gather_facts: no
  roles:
    - role: ../../../external/ansible_playbooks/playbooks/roles/rpi_config_network
      tags: ['configure_rpi_network']
      
    - role: ../../../external/ansible_playbooks/playbooks/roles/dhcp_static_ip
      tags: ['define_static_ip']

  tasks:
    - name: Reboot and wait
      include_tasks: ../../../external/ansible_playbooks/playbooks/reboot.yaml
      tags: ['reboot']
