name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**' # Triggers the workflow on any pull request and on any branch

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  POETRY_VERSION: "2.1.3"

jobs:
  tests:
    name: Test & Promote Plugins
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ '3.11' ]
    
    outputs:
      plugins_json: ${{ steps.detect_changes.outputs.json_response }}

    steps:
      - name: Checkout main provisioner repository
        uses: actions/checkout@v4
        with:
          repository: 'ZachiNachshon/provisioner'
          token: ${{ secrets.PROVISIONER_REPO_ACCESS_TOKEN }}
          submodules: false  # We'll handle submodules manually
          fetch-depth: 2  # Need previous commit to detect changes on push

      - name: Checkout plugins repository to get latest changes
        uses: actions/checkout@v4
        with:
          repository: 'ZachiNachshon/provisioner-plugins'
          token: ${{ secrets.PROVISIONER_REPO_ACCESS_TOKEN }}
          path: plugins
          fetch-depth: 2  # Need previous commit to detect changes

      - name: Setup Environment
        uses: ./.github/actions/setup
        env:
          PYTHON_VERSION: ${{ matrix.python }}
          POETRY_VERSION: ${{ env.POETRY_VERSION }}

      - name: Run Tests
        uses: ./.github/actions/tests
        with:
          include_e2e: false

      - name: Save Unit Test Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: false

      # Only detect changes and create RCs on push to master (not on PRs)
      - name: Detect Changed Plugins
        id: detect_changes
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::group::Detecting changed plugins"
          
          # Use the version manager to detect changed plugins
          # The version manager automatically sets json_response in $GITHUB_OUTPUT
          python3 scripts/github_actions/version_manager.py detect-plugins plugins --plugin-mode --github-repo ZachiNachshon/provisioner-plugins
          
          echo "::endgroup::"

  create_plugin_rcs:
    name: Create RC for Changed Plugins
    runs-on: ubuntu-latest
    needs: tests
    # Only run on push to master when there are plugin changes
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' && needs.tests.outputs.plugins_json != '' && fromJSON(needs.tests.outputs.plugins_json).plugins[0] != null
    strategy:
      matrix:
        plugin: ${{ fromJSON(needs.tests.outputs.plugins_json).plugins }}
    
    steps:              
      - name: Checkout main provisioner repository
        uses: actions/checkout@v4
        with:
          repository: 'ZachiNachshon/provisioner'
          token: ${{ secrets.PROVISIONER_REPO_ACCESS_TOKEN }}
          submodules: false  # We'll handle submodules manually
          fetch-depth: 2  # Need previous commit to detect changes

      - name: Checkout plugins repository to get latest changes
        uses: actions/checkout@v4
        with:
          repository: 'ZachiNachshon/provisioner-plugins'
          token: ${{ secrets.PROVISIONER_REPO_ACCESS_TOKEN }}
          path: plugins
          fetch-depth: 2  # Need previous commit to detect changes

      - name: Check for source code changes
        id: check-changes
        uses: dorny/paths-filter@v2
        with:
          working-directory: plugins
          filters: |
            source:
              - '${{ matrix.plugin }}/**/*.py'
              - '${{ matrix.plugin }}/**/*.yaml'
              - '${{ matrix.plugin }}/**/*.yml'
              - '${{ matrix.plugin }}/**/*.toml'
              - '${{ matrix.plugin }}/**/*.json'
              - '${{ matrix.plugin }}/**/*.sh'
              - '${{ matrix.plugin }}/**/Dockerfile*'
              - '!**/pyproject.toml'
              - '!**/manifest.json'
              - '!**/*.lock'
              - '!**/*.md'
              - '!**/README*'
              - '!**/CHANGELOG*'
              - '!**/LICENSE*'
              - '!**/.gitignore'
              - '!**/.cursorignore'

      - name: Setup Environment
        if: steps.check-changes.outputs.source == 'true'
        uses: ./.github/actions/setup
        env:
          PYTHON_VERSION: '3.11'
          POETRY_VERSION: ${{ env.POETRY_VERSION }}

      - name: Run Tests for Plugin
        if: steps.check-changes.outputs.source == 'true'
        uses: ./.github/actions/tests
        with:
          module_to_test: ${{ matrix.plugin }}
          include_e2e: false

      - name: Promote Plugin to RC
        if: steps.check-changes.outputs.source == 'true'
        uses: ./.github/actions/promote-rc
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          projects: |
            [
              {
                "project_path": "plugins/${{ matrix.plugin }}",
                "is_plugin": true,
                "github_repo": "ZachiNachshon/provisioner-plugins"
              }
            ]
